apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-list
spec:
  replicas: 2
  selector:
    matchLabels:
      app: price-list
  template:
    metadata:
      labels:
        app: price-list
    spec:
      containers:
        - name: price-list
          image: dharshitha123/price-list:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: price-list-service
spec:
  type: NodePort
  selector:
    app: price-list
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010